### ISSUE TITLE
change topic name from "laser_scan" to "scan"

### ISSUE THREAD

**Issue by dwindy** [googlecartographer/cartographer_turtlebot#102]
Hi
I successively run the cartographer_trutlebot_demo.bag.
I recorded my own bag, trying to run the cartographer_turtlebot based on that.

### The terminal outputs
[FATAL] [1582746910.357573635]: Error opening file: all-2020-02-26-18-49-30.bag
....some [INFO] of find the lua
[playbag-5] process has died [pid 9519, exit code 1, cmd /opt/ros/kinetic/lib/rosbag/play --clock all-2020-02-26-18-49-30.bag __name:=playbag __log:=/home/bingxin/.ros/log/e48833da-58d1-11ea-a734-000c29f89067/playbag-5.log].
log file: /home/bingxin/.ros/log/e48833da-58d1-11ea-a734-000c29f89067/playbag-5*.log
[ WARN] [1582746913.431290607]: W0226 19:55:13.000000  9488 node.cc:857] Expected topic "scan" (trajectory 0) (resolved topic "/scan") but no publisher is currently active.
[ WARN] [1582746913.431528522]: W0226 19:55:13.000000  9488 node.cc:857] Expected topic "odom" (trajectory 0) (resolved topic "/odom") but no publisher is currently active.
[ WARN] [1582746913.431689439]: W0226 19:55:13.000000  9488 node.cc:866] Currently available topics are: /move_base_simple/goal,/constraint_list,/submap_list,/scan_matched_points2,/rosout,/initialpose,/tf,/clicked_point,/imu,/rosout_agg,/map,/trajectory_node_list,/landmark_poses_list,

Thank you

**Comment by dwindy** [comment]
Well, I

**Comment by liushuai0901** [comment]
我和你一样遇到了相同的问题，请问您解决了吗？如果解决了可以教教我怎么解决这个问题吗？
