### ISSUE TITLE
About the localisation mode

### ISSUE THREAD

**Issue by JiayanQ** [googlecartographer/cartographer_turtlebot#21]
Thanks for your brilliant work!

I just wonder that can I use the well-built map by the SLAM mode to carry out a navigation or localization work? Because I did not found the code to change the mode for SLAM to Localization in the cartographer_node_main.cc. Should I modify the code in some other documents to achieve the navigation task? Thanks.

And thanks again for this amazing work!!

**Comment by damonkohler** [comment]
Pure localization is not yet supported. However, lifelong mapping, which would negate the usefulness of pure localization, is planned.

The /map topic publishes a nav_msgs/OccupancyGrid that can be used by existing ROS nodes (e.g. navigation and localization).

**Comment by JiayanQ** [comment]
Thanks a lot for your reply.

Cheers,
Jiayan

2016-10-06 22:03 GMT+11:00 Damon Kohler <notifications@github.com>:
