### ISSUE TITLE
2D Mapping with lidar and odometry

### ISSUE THREAD

**Issue by apr8** [googlecartographer/cartographer_turtlebot#59]
Hi,
I have been trying to generate a 2D map using the lidar and odometry data alone.  However I get the following error when I set using odom = true.
error:Check failed: frame_id[0] != '/' ('/' vs. '/')

My configuration is similar to that of pr2 but the enable odom is set true. Am I doing something wrong?

**Comment by SirVer** [comment]
Your `frame_id`s start with a `/`. This is no longer valid in ROS and it never was working as intended anyways. Cartographer refuses these frame id_s (as the error output after the crash should say).

See 1.7 in http://wiki.ros.org/tf2/Migration#Removal_of_support_for_tf_prefix.
