### ISSUE TITLE
File 'trajectory_builder.lua' was not found.

### ISSUE THREAD

**Issue by FelicxFoster** [googlecartographer/cartographer_turtlebot#80]
#why i have this error
i run the "roslaunch cartographer_ros turtlebot_lidar_2d.launch" the terminal place that "[FATAL] [1512705370.945497189]: F1208 11:56:10.000000 22035 configuration_file_resolver.cc:44] File 'trajectory_builder.lua' was not found."   How could i solve it, please help me!

felicx@felicx-Lenovo-XiaoXin-310-14ISK:~/carto_ws$ roslaunch cartographer_ros turtlebot_lidar_2d.launch
... logging to /home/felicx/.ros/log/5327b740-dbcd-11e7-b5a9-ac2b6e7a2f6f/roslaunch-felicx-Lenovo-XiaoXin-310-14ISK-23951.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://felicx-Lenovo-XiaoXin-310-14ISK:41487/

SUMMARY
========

PARAMETERS
 * /app_manager/auto_rapp_installation: False
 * /app_manager/auto_start_rapp: 
 * /app_manager/capability_server_name: capability_server
 * /app_manager/local_remote_controllers_only: False
 * /app_manager/preferred: [{'rocon_apps/chi...
 * /app_manager/rapp_package_blacklist: []
 * /app_manager/rapp_package_whitelist: ['rocon_apps', 't...
 * /app_manager/robot_icon: turtlebot_bringup...
 * /app_manager/robot_name: turtlebot
 * /app_manager/robot_type: turtlebot
 * /app_manager/screen: True
 * /app_manager/simulation: False
 * /app_manager/use_gateway_uuids: False
 * /bumper2pointcloud/pointcloud_radius: 0.24
 * /capability_server/blacklist: ['std_capabilitie...
 * /capability_server/defaults/kobuki_capabilities/KobukiBringup: kobuki_capabiliti...
 * /capability_server/defaults/kobuki_capabilities/KobukiBumper: kobuki_capabiliti...
 * /capability_server/defaults/kobuki_capabilities/KobukiCliffDetection: kobuki_capabiliti...
 * /capability_server/defaults/kobuki_capabilities/KobukiLED1: kobuki_capabiliti...
 * /capability_server/defaults/kobuki_capabilities/KobukiLED2: kobuki_capabiliti...
 * /capability_server/defaults/kobuki_capabilities/KobukiLED: kobuki_capabiliti...
 * /capability_server/defaults/kobuki_capabilities/KobukiWheelDropDetection: kobuki_capabiliti...
 * /capability_server/defaults/std_capabilities/Diagnostics: turtlebot_capabil...
 * /capability_server/defaults/std_capabilities/DifferentialMobileBase: kobuki_capabiliti...
 * /capability_server/defaults/std_capabilities/LaserSensor: turtlebot_capabil...
 * /capability_server/defaults/std_capabilities/RGBDSensor: turtlebot_capabil...
 * /capability_server/defaults/std_capabilities/RobotStatePublisher: turtlebot_capabil...
 * /capability_server/defaults/turtlebot_capabilities/TurtleBotBringup: turtlebot_capabil...
 * /capability_server/nodelet_manager_name: capability_server...
 * /capability_server/package_whitelist: ['kobuki_capabili...
 * /cmd_vel_mux/yaml_cfg_file: /home/felicx/turt...
 * /description: Kick-ass ROS turtle
 * /diagnostic_aggregator/analyzers/input_ports/contains: ['Digital Input',...
 * /diagnostic_aggregator/analyzers/input_ports/path: Input Ports
 * /diagnostic_aggregator/analyzers/input_ports/remove_prefix: mobile_base_nodel...
 * /diagnostic_aggregator/analyzers/input_ports/timeout: 5.0
 * /diagnostic_aggregator/analyzers/input_ports/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/kobuki/contains: ['Watchdog', 'Mot...
 * /diagnostic_aggregator/analyzers/kobuki/path: Kobuki
 * /diagnostic_aggregator/analyzers/kobuki/remove_prefix: mobile_base_nodel...
 * /diagnostic_aggregator/analyzers/kobuki/timeout: 5.0
 * /diagnostic_aggregator/analyzers/kobuki/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/power/contains: ['Battery', 'Lapt...
 * /diagnostic_aggregator/analyzers/power/path: Power System
 * /diagnostic_aggregator/analyzers/power/remove_prefix: mobile_base_nodel...
 * /diagnostic_aggregator/analyzers/power/timeout: 5.0
 * /diagnostic_aggregator/analyzers/power/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/sensors/contains: ['Cliff Sensor', ...
 * /diagnostic_aggregator/analyzers/sensors/path: Sensors
 * /diagnostic_aggregator/analyzers/sensors/remove_prefix: mobile_base_nodel...
 * /diagnostic_aggregator/analyzers/sensors/timeout: 5.0
 * /diagnostic_aggregator/analyzers/sensors/type: diagnostic_aggreg...
 * /diagnostic_aggregator/base_path: 
 * /diagnostic_aggregator/pub_rate: 1.0
 * /icon: turtlebot_bringup...
 * /interactions/interactions: ['turtlebot_bring...
 * /interactions/pairing: True
 * /interactions/rosbridge_address: localhost
 * /interactions/rosbridge_port: 9090
 * /interactions/webserver_address: webapp.robotconce...
 * /mobile_base/base_frame: base_footprint
 * /mobile_base/battery_capacity: 16.5
 * /mobile_base/battery_dangerous: 13.2
 * /mobile_base/battery_low: 14.0
 * /mobile_base/cmd_vel_timeout: 0.6
 * /mobile_base/device_port: /dev/kobuki
 * /mobile_base/odom_frame: odom
 * /mobile_base/publish_tf: True
 * /mobile_base/use_imu_heading: True
 * /mobile_base/wheel_left_joint_name: wheel_left_joint
 * /mobile_base/wheel_right_joint_name: wheel_right_joint
 * /name: turtlebot
 * /robot/name: turtlebot
 * /robot/type: turtlebot
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 5.0
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /turtlebot_laptop_battery/acpi_path: /sys/class/power_...
 * /use_sim_time: False
 * /zeroconf/zeroconf/services: [{'domain': 'loca...

NODES
  /zeroconf/
    zeroconf (zeroconf_avahi/zeroconf)
  /
    app_manager (rocon_app_manager/rapp_manager.py)
    bumper2pointcloud (nodelet/nodelet)
    capability_server (capabilities/capability_server)
    cartographer_node (cartographer_ros/cartographer_node)
    cmd_vel_mux (nodelet/nodelet)
    diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
    flat_world_imu_node (cartographer_ros/cartographer_flat_world_imu_node)
    interactions (rocon_interactions/interactions_manager.py)
    master (rocon_master_info/master.py)
    mobile_base (nodelet/nodelet)
    mobile_base_nodelet_manager (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    turtlebot_laptop_battery (laptop_battery_monitor/laptop_battery.py)

auto-starting new master
process[master]: started with pid [23966]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5327b740-dbcd-11e7-b5a9-ac2b6e7a2f6f
process[rosout-1]: started with pid [23979]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [23997]
process[diagnostic_aggregator-3]: started with pid [23998]
process[mobile_base_nodelet_manager-4]: started with pid [23999]
process[mobile_base-5]: started with pid [24008]
process[bumper2pointcloud-6]: started with pid [24011]
process[cmd_vel_mux-7]: started with pid [24022]
process[turtlebot_laptop_battery-8]: started with pid [24040]
process[capability_server-9]: started with pid [24043]
process[app_manager-10]: started with pid [24056]
process[master-11]: started with pid [24068]
process[interactions-12]: started with pid [24083]
[ERROR] [1512706058.092966655]: Skipping XML Document "/opt/ros/indigo/share/gmapping/nodelet_plugins.xml" which had no Root Element.  This likely means the XML is malformed or missing.
process[zeroconf/zeroconf-13]: started with pid [24086]
process[cartographer_node-14]: started with pid [24112]
ERROR: cannot launch node of type [cartographer_ros/cartographer_flat_world_imu_node]: can't locate node [cartographer_flat_world_imu_node] in package [cartographer_ros]
process[rviz-16]: started with pid [24130]
[ INFO] [1512706058.204131618]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/home/felicx/carto_ws/install_isolated/share/cartographer_ros/configuration_files/turtlebot_urg_lidar_2d.lua' for 'turtlebot_urg_lidar_2d.lua'.
[ INFO] [1512706058.204530682]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[ INFO] [1512706058.204585851]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[ INFO] [1512706058.204676360]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[ INFO] [1512706058.204722193]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[ INFO] [1512706058.204899873]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1512706058.204950355]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1512706058.205124230]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/sparse_pose_graph.lua' for 'sparse_pose_graph.lua'.
[ INFO] [1512706058.205168677]: I1208 12:07:38.000000 24112 configuration_file_resolver.cc:40] Found '/usr/local/share/cartographer/configuration_files/sparse_pose_graph.lua' for 'sparse_pose_graph.lua'.
F1208 12:07:38.205330 24112 configuration_file_resolver.cc:44] File 'trajectory_builder.lua' was not found.
[FATAL] [1512706058.205608069]: F1208 12:07:38.000000 24112 configuration_file_resolver.cc:44] File 'trajectory_builder.lua' was not found.
[ INFO] [1512706059.057698944]: Zeroconf: service successfully established [turtlebot][_ros-master._tcp][11311]
*** Check failure stack trace: ***
    @     0x7fb23990fdaa  (unknown)
    @     0x7fb23990fce4  (unknown)
    @     0x7fb23990f6e6  (unknown)
    @     0x7fb239912687  (unknown)
    @           0x549616  cartographer::common::ConfigurationFileResolver::GetFullPathOrDie()
    @           0x5441e6  cartographer::common::LuaParameterDictionary::LuaInclude()
    @     0x7fb23bbab61d  (unknown)
    @     0x7fb23bbb69b4  (unknown)
    @     0x7fb23bbab989  (unknown)
    @     0x7fb23bbaafac  (unknown)
    @     0x7fb23bbabbc1  (unknown)
    @     0x7fb23bba7c9d  (unknown)
    @           0x54333c  cartographer::common::LuaParameterDictionary::LuaParameterDictionary()
    @           0x54358a  cartographer::common::LuaParameterDictionary::LuaParameterDictionary()
    @           0x4e81bd  cartographer_ros::(anonymous namespace)::Run()
    @           0x4e278d  main
    @     0x7fb237f74f45  (unknown)
    @           0x4e38a7  (unknown)
    @              (nil)  (unknown)
[cartographer_node-14] process has died [pid 24112, exit code -6, cmd /home/felicx/carto_ws/install_isolated/lib/cartographer_ros/cartographer_node -configuration_directory /home/felicx/carto_ws/install_isolated/share/cartographer_ros/configuration_files -configuration_basename turtlebot_urg_lidar_2d.lua scan:=/scan __name:=cartographer_node __log:=/home/felicx/.ros/log/5327b740-dbcd-11e7-b5a9-ac2b6e7a2f6f/cartographer_node-14.log].
log file: /home/felicx/.ros/log/5327b740-dbcd-11e7-b5a9-ac2b6e7a2f6f/cartographer_node-14*.log
[ERROR] [1512706060.200407906]: Skipping XML Document "/opt/ros/indigo/share/gmapping/nodelet_plugins.xml" which had no Root Element.  This likely means the XML is malformed or missing.
================================================================================REQUIRED process [rviz-16] has died!
process has finished cleanly
log file: /home/felicx/.ros/log/5327b740-dbcd-11e7-b5a9-ac2b6e7a2f6f/rviz-16*.log
Initiating shutdown!
================================================================================
[app_manager-10] killing on exit
[rviz-16] killing on exit
[zeroconf/zeroconf-13] killing on exit
[interactions-12] killing on exit
[master-11] killing on exit
[turtlebot_laptop_battery-8] killing on exit
[cmd_vel_mux-7] killing on exit
[bumper2pointcloud-6] killing on exit
[mobile_base-5] killing on exit
[capability_server-9] killing on exit
[mobile_base_nodelet_manager-4] killing on exit
[diagnostic_aggregator-3] killing on exit
[robot_state_publisher-2] killing on exit
Exception in thread Thread-25 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/opt/ros/indigo/lib/python2.7/dist-packages/bondpy/bondpy.py", line 247, in _publishing_thread
  File "/usr/lib/python2.7/threading.py", line 215, in __exit__
  File "/usr/lib/python2.7/threading.py", line 202, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by gaschler** [comment]
First, turtlebot is part of the cartographer_turtlebot project, so `roslaunch cartographer_turtlebot turtlebot.launch` (not _ros).

trajectory_builder.lua is a configuration file provided by cartographer.
Also make sure you follow the catkin install instructions, and do not forget `source install_isolated/setup.bash`.

I'm believe this is resolved, feel free to re-open if necessary.

**Comment by araster1010** [comment]
I have a same problem.

And if I run  `roslaunch cartographer_turtlebot turtlebot.launch` first, the console says below.

[/home/(user name)/catkin_ws/install_isolated/share/cartographer_turtlebot/launch/turtlebot.launch] requires the 'configuration_basename' arg to be set
The traceback for the exception was written to the log file

I'm a beginner at ROS. Could you tell me the meaning of 'configuration_basename' arg  and what shall I do?

Thanks.

**Comment by gaschler** [comment]
configuration_basename is "Basename, i.e. not containing any directory prefix, of the configuration file."
For example, backpack_2d.lua.
Follow https://google-cartographer.readthedocs.io/en/latest/index.html, start with the launch files included and go from there.
