### ISSUE TITLE
Kinect_v2 in cartographer 3D Map using turtlebot2(kobuki) , the topic of Kinect_v2 is /kinect/qhd/points, the launch file is turtlebot_depth_camera_3d.launch

### ISSUE THREAD

**Issue by yueshukun** [googlecartographer/cartographer_turtlebot#97]
When I use these, the scan_matched_points normal display, but no map received, that means cartographer_node do not publish the topic of map, why?

**Comment by gaschler** [comment]
cartographer*_node do not publish `nav_msgs/OccupancyGrid.msg`.
Take a look occupancy_grid_node and in backpack_2/3d.launch how it is started.
Or, for ROS map files (pgm+yaml), see pbstream_to_ros_map.
